spring:
  application:
    name: db-insert
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 10000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        session:
          events:
            log:
              LOG_QUERIES_SLOWER_THAN_MS: 100
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  shell:
    interactive:
      enabled: true

dbinsert:
  data:
    size: 1_000_000
  log:
    batch:
      enabled: false
